name: dslink_macos
description: macOS DSLink
dependencies:
  args: ">=0.12.0 <0.15.0"
  mac:
    git: https://github.com/DirectMyFile/macOS.dart.git
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
